import type { Options } from "qr-code-styling";
import { buildVCard, type VCardInput } from "../vcard";

// "svg" avoids pulling a native `canvas` dependency into the render path
// (either in the browser, where SVG needs no native canvas, or if this
// options object were ever reused for a server-side render). See the module
// doc in `index.ts` for the core-vs-render split this supports.
const QR_DRAW_TYPE = "svg";
const QR_SIZE_PX = 320;
const QR_MARGIN_PX = 8;

// Pre-baked QR centre logo: the org's brand mark on a radial white plate that
// is solid through its inner 80% and fades to fully transparent at the edge, so
// it melts into the QR dots instead of sitting in a hard box. Generated by
// `scripts/make-qr-logo.mjs`; regenerate that asset if the branding changes.
const QR_LOGO_IMAGE_PATH = "/brand/qr-logo.png";

// Relative size of that image within the QR. Because the plate's outer ring is
// transparent, only a smaller circle is actually opaque — well within what
// error-correction level H (~30% recoverable) tolerates.
const LOGO_SIZE_RATIO = 0.35;

/**
 * Builds the `qr-code-styling` `Options` object for a staff card's QR code:
 * the vCard text at error-correction level H, with the centred brand logo.
 * When `photoUrl` is provided, the vCard carries a `PHOTO;VALUE=URI` line — a
 * short URL (the `/avatar/<slug>` endpoint), not the old base64 blob, so the QR
 * stays scannable while still delivering a contact photo on scan.
 *
 * The logo is embedded via the library's `image` option (not a DOM overlay) so
 * an exported/downloaded QR is self-contained. `hideBackgroundDots: false` is
 * deliberate: the square dot-clearing is what produced the blocky white box —
 * instead the transparency baked into the asset does the blending, letting the
 * QR dots show through the plate's faded edge.
 *
 * Pure and side-effect-free — it does not touch the DOM/canvas. Rendering
 * (`new QRCodeStyling(options)` + `.append(container)`) is a browser-only
 * concern left to the Step 4 client component; see `index.ts`.
 */
export function buildQrCodeOptions(input: VCardInput, photoUrl?: string | null): Options {
  // The QR always uses the URI form (a base64 photo would bloat it past
  // scannability); the `.vcf` download embeds base64 instead.
  const photo = photoUrl ? ({ kind: "uri", url: photoUrl } as const) : undefined;
  const data = buildVCard(input, { photo });

  return {
    type: QR_DRAW_TYPE,
    width: QR_SIZE_PX,
    height: QR_SIZE_PX,
    margin: QR_MARGIN_PX,
    data,
    image: QR_LOGO_IMAGE_PATH,
    qrOptions: { errorCorrectionLevel: "H" },
    imageOptions: {
      hideBackgroundDots: false,
      imageSize: LOGO_SIZE_RATIO,
      margin: 0,
    },
    dotsOptions: { type: "square", color: "#000000" },
    backgroundOptions: { color: "#ffffff" },
  };
}
